Sprint 1
Zimer-D/middle.messenger.praktikum.yandex pull request #1
Opened 2022-12-08 12:47 UTC by Zimer-D

2022-12-08 13:10 UTC, Zimer-D commented
netlify APP https://vermillion-sprinkles-a79ac5.netlify.app/

2022-12-08 15:20 UTC, podlovchenko requested changes
Замечания из остаются актуальными
И едет верстка при вводе значения
<img width="495" alt="Снимок экрана 2022-12-08 в 18 15 12" src="https://user-images.githubusercontent.com/22602747/206484115-fb519f02-bd6c-4cb4-a890-7710f3885185.png">

2022-12-08 15:20 UTC, podlovchenko commented on README.md
> +https://app.netlify.com/sites/unique-torrone-670401/deploys/6391c2190a3ddc6f5fc3a4db
Надо указать ссылку на само приложение
Вот эту https://vermillion-sprinkles-a79ac5.netlify.app/

И ссылку на макеты

2022-12-09 08:44 UTC, podlovchenko approved these changes
Спасибо за правки, работу принимаю)

2022-12-13 07:11 UTC, merged